services:
  app:
    build:
      context: .
      dockerfile: docker/Dockerfile
    container_name: wwss_app
    working_dir: /var/www
    volumes:
      - .:/var/www
    networks:
      - wwss_network
    depends_on:
      - mysql

  nginx:
    image: nginx:alpine
    container_name: wwss_nginx
    ports:
      - "8000:80"
    volumes:
      - .:/var/www
      - ./docker/nginx.conf:/etc/nginx/conf.d/default.conf
      - ./.env:/var/www/.env
    depends_on:
      - app
    networks:
      - wwss_network

  mysql:
    image: mysql:8
    container_name: wwss_mysql
    ports:
      - "3307:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: wwss
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - wwss_network

networks:
  wwss_network:

volumes:
  mysql_data:
